// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/13/2026, 5:22:41 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/trancn/projects/trancn/github/profile/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/trancn/projects/trancn/github/profile/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/trancn/projects/trancn/github/profile/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/trancn/projects/trancn/github/profile/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/trancn/projects/trancn/github/profile/plugins/**/*.{js,ts,mjs}","/home/trancn/projects/trancn/github/profile/composables/**/*.{js,ts,mjs}","/home/trancn/projects/trancn/github/profile/utils/**/*.{js,ts,mjs}","/home/trancn/projects/trancn/github/profile/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/trancn/projects/trancn/github/profile/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/trancn/projects/trancn/github/profile/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/trancn/projects/trancn/github/profile/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;